<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_Add Vital Sign</name>
   <tag></tag>
   <elementGuidId>563cc6ba-c84e-4d5d-9e51-e94d48d3a604</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>strong.cursor-pointer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div[2]/div/div/div/div/div/div/strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>92eff156-c3c3-4fea-a664-d2297d20b744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cursor-pointer</value>
      <webElementGuid>faef9c65-dd15-49b9-b593-2ab5354582e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+Add Vital Sign</value>
      <webElementGuid>e6f2075f-619a-41e9-a626-1279696d4b9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;wrapper d-flex flex-column min-vh-100 bg-light&quot;]/div[@class=&quot;body flex-grow-1 px-3&quot;]/div[@class=&quot;container-lg&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;card mb-4&quot;]/div[@class=&quot;card-header p-4 bg-white&quot;]/div[@class=&quot;d-flex justify-content-end&quot;]/strong[@class=&quot;cursor-pointer&quot;]</value>
      <webElementGuid>21ba03b9-5ab6-4724-8944-60981738edaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>952c02ac-ea38-4727-b96c-ac768da0d41a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cursor-pointer</value>
      <webElementGuid>cd811563-a53b-45a5-a012-615454fd2c02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+Add Vital Sign</value>
      <webElementGuid>996be0c8-5d13-4f41-93c9-8cce8927f2cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;wrapper d-flex flex-column min-vh-100 bg-light&quot;]/div[@class=&quot;body flex-grow-1 px-3&quot;]/div[@class=&quot;container-lg&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;card mb-4&quot;]/div[@class=&quot;card-header p-4 bg-white&quot;]/div[@class=&quot;d-flex justify-content-end&quot;]/strong[@class=&quot;cursor-pointer&quot;]</value>
      <webElementGuid>75411e6d-0003-44d0-9ace-e553d7ef070a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div/div/div/div/div/div/strong</value>
      <webElementGuid>c789d9c5-a074-44f7-86a1-8294beda5419</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vital Sign'])[1]/following::strong[1]</value>
      <webElementGuid>25bc2f81-973f-4614-b7bc-f225006108d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blood Pressure'])[1]/preceding::strong[1]</value>
      <webElementGuid>938914d8-48ce-42a7-84f2-1e2de4eebded</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Heart Rate'])[1]/preceding::strong[1]</value>
      <webElementGuid>b4922884-c047-4b9f-a4f2-1f732f9d3992</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='+Add Vital Sign']/parent::*</value>
      <webElementGuid>9ddea6b8-8e33-469c-bdad-0288369d201a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//strong</value>
      <webElementGuid>1973fddf-1139-4ab6-8b9b-4b81290e4f33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = '+Add Vital Sign' or . = '+Add Vital Sign')]</value>
      <webElementGuid>8f942d48-7d3c-4cef-9039-a3552815a4da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
